CREATE TABLE IF NOT EXISTS ALUNO (
  MATRICULA INTEGER(4),
  NOME VARCHAR(20),
  ESCOLA VARCHAR(20),

  PRIMARY KEY (MATRICULA)  
);

CREATE TABLE IF NOT EXISTS DISCIPLINA (
  CODIGO CHAR(5),
  NOME VARCHAR(20),
  REGISTRO CHAR(5),
  ESCOLA VARCHAR(20),

  PRIMARY KEY (CODIGO)  
);

CREATE TABLE IF NOT EXISTS HISTORICO  (
  MATRICULA INTEGER(4),
  CODIGO CHAR(5),
  NOTA DECIMAL(3,1),

  PRIMARY KEY (MATRICULA, CODIGO)  
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
  REGISTRO CHAR(5),
  NOME VARCHAR(20),
  ADMISSAO INTEGER,

  PRIMARY KEY (REGISTRO)  
);

