CREATE TABLE IF NOT EXISTS DEPT (
  ID INTEGER(7) NOT NULL,
  nome VARCHAR(25) NOT NULL,

  PRIMARY KEY (ID)  
);

CREATE TABLE IF NOT EXISTS EMP (
  ID INTEGER(7) NOT NULL,
  NOME VARCHAR(25) NOT NULL,
  SOBRENOME VARCHAR(25) NOT NULL,
  DEPT_ID INTEGER(7),

  PRIMARY KEY (ID),
  FOREIGN KEY (DEPT_ID) REFERENCES DEPT (ID)  
);

ALTER TABLE EMP
MODIFY SOBRENOME VARCHAR(50);

RENAME TABLE EMP TO EMP2;
ALTER TABLE EMP2 DROP COLUMN NOME;
